# Generated by Django 5.1.4 on 2025-01-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_order_orderitem_order_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
