# Generated by Django 5.1.4 on 2025-02-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_product_image_alter_product_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
